version: '3.8'

services:
  backend:
    build: ./backend
    container_name: node_backend
    env_file:
      - ./backend/.env
    ports:
      - "5001:5001"
    restart: always

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always